// USER ACTIONS
export const SET_USER = 'SET_USER'
export const SET_USERS = 'SET_USERS'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'

// UI ACTIONS
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SET_SHOWED_WELCOME_ANIMATION = 'SET_SHOWED_WELCOME_ANIMATION'

// RECOMMENDATION ACTIONS
export const SET_EXPLORE_RECOMMENDATIONS = 'SET_EXPLORE_RECOMMENDATIONS'
export const SET_RECOMMENDATION_CATEGORIES = 'SET_RECOMMENDATION_CATEGORIES'
export const SET_CURRENT_USER_RECOMMENDATIONS = 'SET_CURRENT_USER_RECOMMENDATIONS'
export const SET_CURRENT_USER_PAST_RECOMMENDATIONS = 'SET_CURRENT_USER_PAST_RECOMMENDATIONS'
